expt_dir: experiments
expt_name: layout_sdxl
image_size: 512
test_image_size: 512
trainer_args:
  max_epochs: 500
  accelerator: "gpu"
  devices: [0,1,2,3,4,5,6,7]
  limit_train_batches: 3200
  limit_val_batches: 1
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  precision: 16
  strategy: "deepspeed_stage_2"
diffusion:
  target: pl_trainer.SDXL_mask_reorg.RegionalAttnSDXLTrainingMaskAndBboxReorgAdaptiveText
  params:
    accumulate_grad_batches: 16
    loss_fn: "l2"
    optim_args: 
      lr: 1e-5
      weight_decay: 1e-5
    guidance_scale: 5
    train_image_size: ${image_size}
    test_image_size: ${test_image_size}
    num_ddim_steps: 20
    attention_weight_scale: 1.0
    use_ema: True
    ema_decay: 0.99
    ema_start: 100
pipe:
  target: pipelines.sdxl_pipeline.StableDiffusionXLRegionalAttnPipeline
  params: 
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
    add_watermarker: False
    use_safetensors: True
    variant: fp16
vae:
  target: diffusers.AutoencoderKL
  params:
    pretrained_model_name_or_path: 'madebyollin/sdxl-vae-fp16-fix'
scheduler:
  target: diffusers.DDIMScheduler
  params:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
    subfolder: "scheduler"
unet:
  target: regional_attention.diffusers_unet.UNet2DConditionModel
  params:
    position_net_cls: regional_attention.regional_attention.TextEmbeddingNetV2
    fuser_cls: regional_attention.regional_attention.RegionalCrossAttention
    pretrained_model_name_or_path: "regional_attn_sdxl_512_init_weights"
data:
  batch_size: 2
  val_batch_size: 1
  train_shuffle: true
  val_shuffle: true
  collate_fn: 
    target: diffusion_dataset.dataset_utils.custom_collate_fn
  train:
    target: diffusion_dataset.dataset_utils.JointDatasetWithRegionReorg
    params:
      mode: "train"
      sampling_rates:
        - 1.
        - 2.
      subdatasets:
        - target: diffusion_dataset.COCOStuff.CocoStuffBboxCaptionDataset
          params: 
            root: ../DetailedSD/data/coco_2017/
            image_size: ${image_size}
            validation: false
            min_objects_per_image: 1
            max_objects_per_image: 30
            min_object_size: 0.01
        - target: diffusion_dataset.CC3M_synthetic.CC3MSyntheticDataset
          params: 
            root: /home/ubuntu/CC3M
            synthetic_data_dir: /home/ubuntu/instdiff_data_generation/cc3m_generated_data_768
            meta_name: 'meta_2024_4_22.json'
            image_size: ${image_size}
            validation: false
  val:
    target: diffusion_dataset.dataset_utils.JointDatasetWithRegionReorg
    params:
      mode: "val"
      sampling_rates:
        - 1.
        - 2.
      subdatasets:
        - target: diffusion_dataset.COCOStuff.CocoStuffBboxCaptionDataset
          params: 
            root: ../DetailedSD/data/coco_2017/
            image_size: ${test_image_size}
            validation: true
        - target: diffusion_dataset.CC3M_synthetic.CC3MSyntheticDataset
          params: 
            root: /home/ubuntu/CC3M
            synthetic_data_dir: /home/ubuntu/instdiff_data_generation/cc3m_generated_data_768
            meta_name: 'meta_2024_4_22.json'
            image_size: ${image_size}
            validation: true
callbacks:
  - target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      dirpath: "${expt_dir}/${expt_name}"
      filename: "{epoch:04d}"
      monitor: epoch
      mode: max
      save_top_k: 2
      save_last: true
  - target: callbacks.training_visualizer.TrainingLogger
    params:
      max_num_images: 8
    require_wandb: true
  - target: callbacks.script_callback.ChildrenNodeOnlyScriptCallback
    params:
      script_path: misc_utils/delete_legacy_optimizer_states.sh
      script_args: "${expt_name}"